﻿insert into Quiz (chapterID, quizName, position) values (6, N'Trắc nghiệm về HTML', 6)

insert into Question (content, explaination, quizID) values (N'Thuộc tính HTML nào xác định một văn bản sẽ dùng thay thế cho hình ảnh, nếu hình ảnh không thể được hiển thị?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (1, N'alt', 1)
insert into [Option] (questionID, content, isTrue) values (1, N'src', 0)
insert into [Option] (questionID, content, isTrue) values (1, N'title', 0)
insert into [Option] (questionID, content, isTrue) values (1, N'longdesc', 0)
insert into Question (content, explaination, quizID) values (N'Các chú thích HTML (comment) bắt đầu bởi <!-- và kết thúc bởi -->', N'', 1)
insert into [Option] (questionID, content, isTrue) values (2, N'True', 1)
insert into [Option] (questionID, content, isTrue) values (2, N'False', 0)
insert into Question (content, explaination, quizID) values (N'Thẻ HTML nào tạo ra một danh sách đổ xuống (drop-down list)?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (3, N'<select>', 1)
insert into [Option] (questionID, content, isTrue) values (3, N'<list>', 0)
insert into [Option] (questionID, content, isTrue) values (3, N'<input type="list">', 0)
insert into [Option] (questionID, content, isTrue) values (3, N'<input type="dropdown">', 0)
insert into Question (content, explaination, quizID) values (N'Phần tử HTML nào thực hiện xuống dòng mới?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (4, N'<lb>', 0)
insert into [Option] (questionID, content, isTrue) values (4, N'<br>', 1)
insert into [Option] (questionID, content, isTrue) values (4, N'<break>', 0)
insert into [Option] (questionID, content, isTrue) values (4, N'<p>', 0)
insert into Question (content, explaination, quizID) values (N'Thẻ HTML nào dùng để chèn hình ảnh vào trang web?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (5, N'<img>image.gif</img>', 0)
insert into [Option] (questionID, content, isTrue) values (5, N'<img src="image.gif">', 1)
insert into [Option] (questionID, content, isTrue) values (5, N'<image src="image.gif">', 0)
insert into [Option] (questionID, content, isTrue) values (5, N'<img href="image.gif>', 0)
insert into Question (content, explaination, quizID) values (N'Đoạn HTML nào là đúng để tạo một liên kết?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (6, N'<a href="https://www.youtube.com/">Xem ở đây</a>', 1)
insert into [Option] (questionID, content, isTrue) values (6, N'<a>https://www.youtube.com/</a>', 0)
insert into [Option] (questionID, content, isTrue) values (6, N'<a name="https://www.youtube.com/">Xem ở đây</a>', 0)
insert into [Option] (questionID, content, isTrue) values (6, N'<a url="https://www.youtube.com/">Xem ở đây</a>', 0)
insert into Question (content, explaination, quizID) values (N'Đâu là phần tử HTML tạo ra 1 danh sách đầu mục bằng số?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (7, N'<list>', 0)
insert into [Option] (questionID, content, isTrue) values (7, N'<ul>', 0)
insert into [Option] (questionID, content, isTrue) values (7, N'<dl>', 0)
insert into [Option] (questionID, content, isTrue) values (7, N'<ol>', 1)
insert into Question (content, explaination, quizID) values (N'Chọn phần tử HTML nào đúng nhất cho định dạng tiêu đề là lớn nhất?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (8, N'<heading>', 0)
insert into [Option] (questionID, content, isTrue) values (8, N'<h6>', 0)
insert into [Option] (questionID, content, isTrue) values (8, N'<h1>', 1)
insert into [Option] (questionID, content, isTrue) values (8, N'<head>', 0)
insert into Question (content, explaination, quizID) values (N'Ký tự nào dùng để kết thúc một thẻ trong HTML?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (9, N'<', 0)
insert into [Option] (questionID, content, isTrue) values (9, N'^', 0)
insert into [Option] (questionID, content, isTrue) values (9, N'*', 0)
insert into [Option] (questionID, content, isTrue) values (9, N'/', 1)

update Question set status = 0 where questionID = 9

insert into Question (content, explaination, quizID) values (N'Chọn phần tử HTML đúng nhất để diễn mức quan trọng của văn bản?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (10, N'<strong>', 1)
insert into [Option] (questionID, content, isTrue) values (10, N'<b>', 0)
insert into [Option] (questionID, content, isTrue) values (10, N'<i>', 0)
insert into [Option] (questionID, content, isTrue) values (10, N'<important>', 0)

insert into Question (content, explaination, quizID) values (N'Thẻ nào sau đây không yêu cầu thẻ đóng?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (11, N'<br>', 1)
insert into [Option] (questionID, content, isTrue) values (11, N'<hr>', 1)
insert into [Option] (questionID, content, isTrue) values (11, N'<input>', 0)


insert into Question (content, explaination, quizID) values (N'Thẻ nào sau đây không yêu cầu thẻ đóng?', N'', 1)
insert into [Option] (questionID, content, isTrue) values (12, N'<br>', 1)
insert into [Option] (questionID, content, isTrue) values (12, N'<hr>', 1)
insert into [Option] (questionID, content, isTrue) values (12, N'<input>', 0)
insert into [Option] (questionID, content, isTrue) values (12, N'<br>1', 1)
insert into [Option] (questionID, content, isTrue) values (12, N'<hr>1', 1)
insert into [Option] (questionID, content, isTrue) values (12, N'<input>', 0)